# fly.toml file generated for dating-jodi on 2023-04-05T18:10:24+01:00

app = "dating-jodi"
kill_signal = "SIGINT"
kill_timeout = 5
mounts = []
primary_region = "lhr"
processes = []

[build]
  image = "bhupendragurung/datingapp:latest"

[env]
  ASPNETCORE_URLS="http://+:8080" 
  CloudinarySettings__CloudName="dbucbpjsf"
  CloudinarySettings__ApiKey="767247489753175"
[[services]]
  internal_port = 8080
  processes = ["app"]
  protocol = "tcp"
  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

  [[services.ports]]
    force_https = true
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443
